### ISSUE TITLE
Make: [docker-corpus-add] Error 137

### ISSUE THREAD

**Issue by carstenhag** [lidel/meowkov#10]
```
[carstenh@archmoter8 bapc_meowkov]$ cat \#reddit-buildapc/bapc.log | sudo make docker-corpus-add
docker start meowkov_corpus
meowkov_corpus
docker start meowkov_irc
meowkov_irc
docker run -v /home/carstenh/git/bapc_meowkov/meowkov.conf:/meowkov/meowkov.conf:ro --link meowkov_corpus:redis -i --rm meowkov -import=true -purge=false
2015/08/15 13:06:09 IMPORT: loading piped data into corpus at localhost:6379
Makefile:43: recipe for target 'docker-corpus-add' failed
make: *** [docker-corpus-add] Error 137
```

Hey, second time loading stuff into the corpus. This time about 143MB of IRC logs from one channel. After some minutes importing it spit out this error code but I'm not sure what could have caused that.

Is there a way to debug this?

**Comment by lidel** [comment]
Nice! My test corpus was 10 times  smaller :-)) I reproduced the error with 150MB one and what I think is happening is that there are more goroutines than Redis is able to serve. 
I added a buffered channel in https://github.com/lidel/meowkov/commit/7aa45d08a76af5467df33f7d00376d38d644a87b which limits the number of goroutines during corpus import and the issue seems to be fixed on my box.

Please run `make docker-rebuild` and let me know  if it fixed it for you too. :rocket:

**Comment by carstenhag** [comment]
```
2015/08/15 17:33:18 IMPORT: loading piped data into corpus at localhost:6379
2015/08/15 17:36:36 IMPORT finished, processed 2340625 lines
```

Yay! Issue got fixed, lovely.
